### ISSUE TITLE
TestSupplychain.js failed on web3.toWei(1, 'ether')

### ISSUE THREAD

**Issue by smaeung** [udacity/nd1309-Project-6b-Example-Template#3]
Error as below with TestSupplychain.js 
```
  Using network 'development'.

TypeError: web3.toWei is not a function
    at /Users/smaeung/Downloads/nd1309-Project-6b-Example-Template-master/project-6/test/TestSupplychain.js:17:31
    at Suite.template (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:220:1)
    at Suite.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:224:57)
    at Object.create (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/interfaces/common.js:112:19)
    at Function.context.describe.context.context (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at global.contract (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:224:1)
    at Object.<anonymous> (/Users/smaeung/Downloads/nd1309-Project-6b-Example-Template-master/project-6/test/TestSupplychain.js:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:536:10)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:118:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Truffle v5.0.5 (core: 5.0.5)
Node v8.11.3
```
 is it becuase web3.toWei() was updated to web3.utils.toWei() ?  or which version was used for w3 ? 

[web3.utils](https://web3js.readthedocs.io/en/1.0/web3-utils.html)

my configuration version as below
```
truffle version
Truffle v5.0.5 (core: 5.0.5)
Solidity - 0.4.24 (solc-js)
Node v8.11.3
```

**Comment by smaeung** [comment]
found out the project was based on Truffle v4.x,  switched to Truffle v4.x, and compiled and test passed.
